version: '3.8'

services:
  pg:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_URL
    volumes: # create a bind mount to pass file that executes tablea creation by SQL
      - ./sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - pgdata:/var/lib/postgresql/data

  webapp: 
    build:
      context: .
      dockerfile: Dockerfile
    volumes: # to mount bind the code (and get the db logs)
      - .:/app
    # ports: # remove if multiple instances of the app are run
    #   - 9292:9292
    depends_on: 
      - pg
    environment:
      - POSTGRES_URL

  webserver:
    # image: ndrean/weberserver:latest
    build: 
      context: ./webserver
      dockerfile: Dockerfile
    depends_on:
      - webapp
    volumes: # to mount bind the static files for Nginx to serve isntead of Puma
      - ./public:/usr/share/nginx/html:ro
    environment:
      - PROXY_UPSTREAM
    ports:
      - 8080:8080
    command: nginx -g 'daemon off;'

  # client:
  #   image:
  #   build: 
  #     context: ./client
  #     dockerfile: Dockerfile
  #   environment:
  #     - POSTGRES_DB
  #     - POSTGRES_PASSWORD
  #     - POSTGRES_USER
  #     - POSTGRES_HOST

volumes:
  pgdata:

