version: '3.8'

services:
  pg:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=test
    volumes: # create a bind mount to pass file that executes SQL
      - ./sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - pgdata:/var/lib/postgresql/data

  webapp: 
    image: webapp:wait_for_pg
    build:
      context: .
      dockerfile: Dockerfile
    volumes: # to mont bind the code
      - .:/app
    ports:
      - 9292:9292
    depends_on: 
      - pg
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER

  webserver:
    build:
      context: ./webserver
      dockerfile: Dockerfile
    depends_on:
      - webapp
    ports:
      - 8080:8080
    command: nginx -g 'daemon off;'

  
volumes:
  pgdata:

