version: '3.8'

services:
  pg:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrs
      - POSTGRES_DB=test
    volumes: # create a bind mount to pass file that executes SQL
      - ./sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - pgdata:/var/lib/postgresql/data

  webapp: 
    image: webapp:wait_for_pg
    build:
      context: .
      dockerfile: Dockerfile
    volumes: # to mont bind the code and get the db logs
      - .:/app
    # ports:
    #   - 9292:9292
    depends_on: 
      - pg
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_URL

  webserver:
    image: weberserver:wait_for_webapp
    build: 
      context: ./webserver
      dockerfile: Dockerfile
    depends_on:
      - webapp
    volumes:
      - ./public:/usr/share/nginx/html:ro
    ports:
      - 8080:8080
    command: nginx -g 'daemon off;'

  
volumes:
  pgdata:

